version: '3'

services:
  frontend:
    restart: always
    container_name: survey_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    volumes:
      - ./frontend/src:/frontend/src

  backend:
    restart: always
    container_name: survey_backend
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/backend
    env_file:
      - .env
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
